export const POLICY_BUNDLE_SCHEMA_VERSION = "1.0.0";
export const RULE_MANIFEST_SCHEMA_VERSION = "1.0.0";
export const AUDIT_EVENT_SCHEMA_VERSION = "1.0.0";
export const DEVICE_ENROLLMENT_SCHEMA_VERSION = "1.0.0";
export const ROLLOUT_STATE_SCHEMA_VERSION = "1.0.0";
